### ISSUE TITLE
Add Dependabot

### ISSUE THREAD

**Issue by jabrena** [jabrena/setup-cli#78]
```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
```
